"""empty message

Revision ID: 4af6a8362325
Revises: fab00963c606
Create Date: 2024-06-07 23:25:46.988818

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4af6a8362325'
down_revision = 'fab00963c606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('set', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_data', schema=None) as batch_op:
        batch_op.drop_column('weight')
        batch_op.drop_column('set')

    # ### end Alembic commands ###
