"""squat data

Revision ID: a259b9fbf0f8
Revises: 95869e3efaa1
Create Date: 2024-06-27 04:42:57.928188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a259b9fbf0f8'
down_revision = '95869e3efaa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left_knee_innerbody', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('right_knee_innerbody', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_data', schema=None) as batch_op:
        batch_op.drop_column('right_knee_innerbody')
        batch_op.drop_column('left_knee_innerbody')

    # ### end Alembic commands ###
