"""Add log data

Revision ID: fab00963c606
Revises: initial_migration_with_all_changes
Create Date: 2024-05-29 00:41:23.113255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fab00963c606'
down_revision = 'initial_migration_with_all_changes'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('log_data', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exercise_data', schema=None) as batch_op:
        batch_op.drop_column('log_data')

    # ### end Alembic commands ###
